let button = document.querySelector("button");
let container = document.querySelector("#container");

    //adds an event listener to the button element, when clicked, the function inside the arrow function will execute.
    button.addEventListener("click", () => {
    
    //creates a new <div> element and assigns it to the variable circle
    const circle = document.createElement("div");
    
    //adds the class "circle" to the newly created circle element.
    circle.classList.add("circle");
    
    //sets the background color of the circle element to a random color generated by the getRandomColor function
    circle.style.backgroundColor = getRandomColor();
    
    //calls the setCirclePositionAndSize function with the circle element as an argument, which positions and sizes the circle within the container.
    setCirclePositionAndSize(circle);
    
    //appends the circle element to the container element, adding it to the DOM
    container.appendChild(circle);
});

function getRandomColor() {
    //returns a random hexadecimal color code by generating a random number & converting it
    return "#" + Math.floor(Math.random() * 16777215).toString(16);
}

function setCirclePositionAndSize(circle) {
    //lines retrieve the width and height of the container element
    const containerWidth = container.offsetWidth;
    const containerHeight = container.offsetHeight;
    
    //calculates the size of the circle element as 10% of the minimum dimension of the container
    const circleSize = Math.min(containerWidth, containerHeight) * 0.10; 
    
    //generate random X and Y coordinates for the position of the circle element, limiting it to 80% of the container's width and height
    const randomX = Math.floor(Math.random() * 80);
    const randomY = Math.floor(Math.random() * 80);

    // set the width, height, position, and styling properties of the circle element to display it properly within the container
    circle.style.width = circleSize + "px"
    circle.style.height = circleSize + "px";
    circle.style.left = randomX + "%";
    circle.style.top = randomY + "%";
    circle.style.borderRadius = "50%";
    circle.style.position = "absolute";
}
